add test
kdv777/Training_portal pull request #86
Opened 2023-11-04 20:07 UTC by korado2022

добавил тесты
в README прописал команду для запуска тестов

2023-11-04 22:09 UTC, juliyamakutu requested changes

2023-11-04 22:09 UTC, juliyamakutu commented on src/mainapp/views.py
> +        context["lessons_course"] = Lesson.objects.all().filter(course=pk)
```suggestion
        context["lessons_course"] = Lesson.objects.filter(course=pk)
```

2023-11-05 06:59 UTC, korado2022 reviewed
Поправил

2023-11-05 10:46 UTC, juliyamakutu approved these changes

2023-11-05 11:08 UTC, merged