Документация к проекту
kdv777/Training_portal pull request #94
Opened 2023-11-07 21:02 UTC by romik1981

Прикладываю документацию созданную с помощью Sphinx

2023-11-08 10:00 UTC, juliyamakutu requested changes

2023-11-08 10:00 UTC, juliyamakutu commented on src/documentation_project/source/conf.py
> +author = 'Belyakov_Roman'
```suggestion
copyright = '2023, Pythons'
author = 'Pythons'
```

2023-11-08 12:45 UTC, romik1981 reviewed
всё правильно

2023-11-08 21:48 UTC, juliyamakutu approved these changes

2023-11-08 21:48 UTC, merged

2023-11-09 06:02 UTC, romik1981 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Создание документации проекта [0.5]](https://trello.com/c/FPzSjoPK/143-5-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-05)

2023-11-09 06:02 UTC, romik1981 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Создание документации проекта [0.5]](https://trello.com/c/FPzSjoPK/143-5-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-05)

2023-11-09 06:02 UTC, romik1981 commented
![](https://github.trello.services/images/mini-trello-icon.png) [(5) Создание документации проекта [0.5]](https://trello.com/c/FPzSjoPK/143-5-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BE%D0%BA%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D0%B0-05)